### ISSUE TITLE
Allow clearing channel cache

### ISSUE THREAD

**Issue by sebamarynissen** [memo33/sc4pac-gui#14]
Would it be possible to implement a "clear cache" for all channels? With this I mean that the contents of the channels are fetched again. I think you mentioned on Simtropolis that they are refetched every 30 minutes.

Now that I have something basic working for the [Simtropolis channel](https://github.com/sebamarynissen/simtropolis-channel), it would be useful for me to be able to clear the cache for testing purposes. Currently it's not always clear whether something's wrong with my deployment, or whether the contents are still cached.

**Comment by memo33** [comment]
Yes, I guess. Though I suppose it would mainly be useful for developers.

For the time being, you can clear the cache for a channel manually by deleting the contents file from your cache directory, for example:
```
./coursier/https/sebamarynissen.github.io/simtropolis-channel/channel/sc4pac-channel-contents.json
```

**Comment by sebamarynissen** [comment]
Mostly for developers indeed, but I would also say for creators. Especially in the beginning of the Simtropolis channel they might wonder whether all this magic has even worked, and when they don't immediately see their package appearing in the sc4pac gui, they might think it didn't. So it's something that I would add - perhaps hidden under an "Advanced" tab or whatever - and then clearly document in the documentation on how to add packages to the Simtropolis channel.

**Comment by memo33** [comment]
This is what I have now:

![2024-12-21_22 11 38](https://github.com/user-attachments/assets/026cdc0a-88db-4d06-8bd2-c77ef9604226)
