### ISSUE TITLE
Sort variants alphabetically

### ISSUE THREAD

**Issue by Zasco** [memo33/sc4pac-gui#7]
The variants are currently sorted randomly. Variants with the same domain are not grouped together which makes it harder to overview.

**Comment by Zasco** [comment]
> Where do want them to be sorted? They are sorted in the dashboard.
They are listed in the dashboard, yes, but not sorted there.

**Comment by memo33** [comment]
They are sorted. Global first, local second. Capital letters come before lowercase letters in ASCII. Do you have an example for the following, as I don't see it:

> Variants with the same domain are not grouped together which makes it harder to overview.

**Comment by Zasco** [comment]
> They are sorted. Global first, local second. Capital letters come before lowercase letters in ASCII.

Haaa, right, I see. The uppercase/lowercase ordering made me believe otherwise. This distinction should be discarded however. Also, I agree with grouping by "_global_" and "_local_", but it should be indicated (as in a group header).

> Do you have an example for the following, as I don't see it:
>> Variants with the same domain are not grouped together which makes it harder to overview.

Yes, here (**sc4c**):
![Unsorted per-package variant](https://github.com/user-attachments/assets/3b09b087-f90b-4330-85f3-e470b52229c0)
It must be because `sc4c:date:sync:enabled` has a 4th component...

**Comment by memo33** [comment]
> It must be because sc4c:date:sync:enabled has a 4th component...

The third colon is not currently valid syntax. The linter would complain.

**Comment by Zasco** [comment]
> > It must be because sc4c:date:sync:enabled has a 4th component...
> 
> The third colon is not currently valid syntax. The linter would complain.

I haven't run the linter on that channel since this feature/standard was added. I will make the required changes. I think these should rather be dot-separated global?

What about this?:
> Also, I agree with grouping by "global" and "local", but it should be indicated (as in a group header).

I think this issue could be closed and this specific change transferred to #8.

**Comment by memo33** [comment]
If there is a `sc4c:date` package, name it `sc4c:date:sync.enabled`. Otherwise, you can use `sc4c:date.sync.enabled`. Or use hyphens instead of dots.

The issue can stay open for now.
